name: Push & Deploy
on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aaraz/primage:devote
          platforms: linux/amd64,linux/arm64
          build-args: |
            "KINDE_CLIENT_ID=${{ secrets.KINDE_CLIENT_ID }}"
            "KINDE_CLIENT_SECRET=${{ secrets.KINDE_CLIENT_SECRET }}"
            "KINDE_ISSUER_URL=${{ secrets.KINDE_ISSUER_URL }}"
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd devote_deployement && docker-compose down && docker-compose pull && docker-compose up -d
